version: '2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/html/:/home/nginx/html/
    environment:
      - TZ=Asia/Shanghai
    networks:
      - blogyg

networks:
  blogyg:
    driver: bridge
